### ISSUE TITLE
Failed host lookup: 'api.track.toggl.com' on Android

### ISSUE THREAD

**Issue by herkyl** [BirjuVachhani/toggl_target#2]
Hey!

Trying out the app but I'm unable to log authenticate. I get this error when I try API key as well as email/pw:
`Failed host lookup: 'api.track.toggl.com'`

I also see _Webpage not available net::ERR_CACHE_MISS_ when I click on any of the pages that link to toggl webapp.

**Comment by BirjuVachhani** [comment]
@herkyl Are you trying on emulator or real device?

**Comment by herkyl** [comment]
On a real device (Pixel 7)

**Comment by BirjuVachhani** [comment]
@herkyl I have released a new version that should work just fine.

**Comment by herkyl** [comment]
Thanks! It worked 👍 

Btw, the Download APK button points to the previous release.

<img width="228" alt="Screenshot 2023-02-13 at 09 11 33" src="https://user-images.githubusercontent.com/714950/218393806-27322880-522e-47be-af9d-4df6f0636787.png">

**Comment by BirjuVachhani** [comment]
I completely forgot about that. Thanks for pointing it out. Its updated now.
